name: Wedaeri Autobot Trigger

on:
  repository_dispatch:
    types: [external_trigger]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Packages
        run: pip install pandas numpy yfinance gspread google-auth requests
      - name: Run Bot
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python Wedaeri_Autobot.py
